### ISSUE TITLE
goagen command help output no longer displays subcommands

### ISSUE THREAD

**Issue by bketelsen** [raphael/goa#81]
goagen --help
usage: codegen help [<command>...]

Show help.

Flags:
      --help                   Show context-sensitive help (also try --help-long and --help-man).
      --version                Show application version.
  -o, --out="/home/bketelsen"  output directory
  -d, --design=DESIGN          design package path
      --debug                  enable debug mode

Args:
  [<command>]  Show help on command.

Subcommands:
{END of output from help command}

**Comment by raphael** [comment]
I'm not able to repro with the latest master, could you confirm this is fixed? Here is what I get:
```
 ~/g/s/g/r/g/goagen $ goagen --help
usage: codegen --design=DESIGN [<flags>] <command> [<args> ...]

The goagen tool generates various artifacts from a goa service design package.

Each command supported by the tool produces a specific type of artifacts. For
example the "app" command generates the code that supports the service
controllers.

The "bootstrap" command runs the "app", "main" and "swagger" commands
generating the controllers supporting code and main skeleton code (if not
already present) as well as the API Swagger specification.

Flags:
      --help           Show context-sensitive help (also try --help-long and
                       --help-man).
      --version        Show application version.
  -o, --out="/home/raphael/go/src/github.com/raphael/goa/goagen"  
                       output directory
  -d, --design=DESIGN  design package path
      --debug          enable debug mode

Commands:
  help [<command>...]
    Show help.

  bootstrap [<flags>]
    Bootstrap command, equivalent to running "app", "main" and "swagger" commands
    sequentially.

  app [<flags>]
    Generate application code

  main [<flags>]
    Generate application main skeleton

  client [<flags>]
    Generate API client tool and package

  swagger
    Generate swagger representation, see http://swagger.io

  schema [<flags>]
    Generate application JSON schema controller

  gen --pkg-path=PKG-PATH [<flags>]
    Invoke third party generator
```

**Comment by bketelsen** [comment]
Maybe it's a dependency problem?  I deleted my raphael/goa directory and did a fresh `go get -a github.com/raphael/goa` then `go install github.com/raphael/goa/goagen` and I still get the same output which is missing almost all of the help commands.

**Comment by raphael** [comment]
Ah yes indeed, I was able to repro after doing a `go get -u gopkg.in/alecthomas/kingpin.v2`. The good news is that @on99's fix worked! Thank you both.

**Comment by bketelsen** [comment]
sweet!
